### ISSUE TITLE
Fee : After applying fee, apply fee structure icon is not in green colour 

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#52]
1. create fee
2. apply fee 

![Screenshot (13)](https://user-images.githubusercontent.com/54258985/63410121-33daaa00-c410-11e9-9c6c-df3703d74803.png)

**Comment by srikanth340** [comment]
Cause : After all fees are applied individually, not calling update fee structure function because of that fee structure is not updated as applied. When user try to apply the fee structure there is no unapplied fees in the list because of it, fee structure is not updating as applied.

Solution : After all fees are applied individually, updating the fee structure to applied by calling updateFeeStrcture(). This will make the fee structure as applied, So that user no need to click apply fee structure.

**Comment by urmadhan** [comment]
Fixed
