### ISSUE TITLE
Fee : after applying all fees, apply fee structure is not working

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#53]
1. create fee and apply
2. click on apply fee structure

**Comment by srikanth340** [comment]
This issue is related to issue no :52

**Cause :** After all fees are applied individually, then user try to apply the fee structure it will try to create the feeSchedules for unapplied fees. Hence all fees are applied then it is not creating any feeSchedules because of it feeStructure is not updating.

**Solution :** After all fees are applied individually, updating the fee structure to applied by calling updateFeeStrcture() automatically. This will make the fee structure as applied, So that user no need to click apply fee structure.

**Comment by urmadhan** [comment]
Fixed
